 export const ActionTypes = {
    //Account Actions
    REGISTER_NEW_USER: 'REGISTER_NEW_USER',
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    DELETE_USER: 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER',

    //User account setup
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
    DELETE_USER_DETAILS: 'DELETE_USER_DETAILS',

    //Video Actions
    //fetch actions
    FETCH_VIDEOS: 'FETCH_VIDEOS',
    FETCH_VIDEOS_BY_SONG: 'FETCH_VIDEOS_BY_SONG',
    FETCH_VIDEOS_BY_USER: 'FETCH_VIDEOS_BY_USER',
    //deform actions
    ADD_VIDEO: 'ADD_VIDEO',
    DELETE_VIDEO: 'DELETE_VIDEO',
    UPDATE_VIDEO: 'UPDATE_VIDEO',
    UPDATE_VIDEO_LIKES: 'UPDATE_VIDEO_LIKES',
    UPDATE_VIDEO_COMMENTS: 'UPDATE_VIDEO_COMMENTS',

    //Video Like Actions
    LIKE_VIDEO: 'LIKE_VIDEO',
    DELETE_LIKE_VIDEO: 'DELETE_LIKE_VIDEO',
    FETCH_VIDEO_LIKES: 'FETCH_VIDEO_LIKES',
    FETCH_USER_VIDEO_LIKES: 'FETCH_USER_VIDEO_LIKES',

    //Message Actions
    FETCH_MESSAGES_TO_USER: 'FETCH_MESSAGES_TO_USER',
    FETCH_MESSAGES_BY_USER: 'FETCH_MESSAGES_BY_USER',
    ADD_NEW_MESSAGE: 'SEND_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',

    //Notification Actions
    FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
    CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',

    //Follow actions
    FOLLOW_USER: 'FOLLOW_USER',
    DELETE_FOLLOW_USER: 'DELETE_FOLLOW_USER',

    //Video Comment Actions
    FETCH_VIDEO_COMMENTS: 'FETCH_VIDEO_COMMENTS',
    ADD_VIDEO_COMMENT: 'ADD_VIDEO_COMMENT',
    DELETE_VIDEO_COMMENT: 'DELETE_VIDEO_COMMENT',

    //Comment Like Actions
    LIKE_COMMENT: 'LIKE_COMMENT',
    UNLIKECOMMENT: 'UNLIKECOMMENT',


    //Comment reply Actions
    ADD_COMMENT_REPLY: 'ADD_COMMENT_REPLY',
    FETCH_COMMENT_REPLIES: 'FETCH_COMMENT_REPLIES',
    DELETE_COMMENT_REPLY: 'DELETE_COMMENT_REPLY',

    //Reply Like Actions
    LIKE_REPLY: 'LIKE_REPLY',
    DELETE_LIKE_REPLY: 'DELETE_LIKE_REPLY',

}