export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from '../Feed'
//export { default as Record } from '../camera/Record'
//export { default as RecordStack } from '../../navigations/stacks/CameraStack'
